import type { Metadata } from "next";
import { cn } from "@/lib/utils";

import "./globals.css";
import { Nav } from "@/components/Nav";
import { inter } from "@/Fonts/Fonts";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="pl">
            <body
                className={cn(
                    "bg-background min-h-screen font-sans antialiased",
                    inter.variable
                )}
            >
                <Nav />
                <main>{children}</main>
                <div className="h-[200vh]" />
            </body>
        </html>
    );
}
