import type { Metadata } from "next";
import { cn } from "@/lib/utils";

import "./globals.css";
import { Nav } from "@/components/Nav";
import { cormorant } from "@/Fonts/Fonts";
import HeaderInfo from "@/components/HeaderInfo";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="pl">
            <body
                className={cn(
                    "bg-[##FFFFFF] min-h-screen font-sans antialiased",
                    cormorant.variable
                )}
            >
                <HeaderInfo />
                <Nav />
                <main className="w-full overflow-x-hidden">{children}</main>
                <div className="h-[200vh]" />
            </body>
        </html>
    );
}
